export const TOGGLE_BURGER_MENU = 'TOGGLE_BURGER_MENU';
export const GET_POSTS_ACTIONS = 'GET_POSTS_ACTIONS';
export const SET_POSTS_ACTIONS = 'SET_POSTS_ACTIONS';
// export const GET_COMMENT_BY_POST_ID = 'GET_COMMENT_BY_POST_ID';
export const GET_ALL_COMMENT_ACTIONS = 'GET_ALL_COMMENT_ACTIONS';
export const SET_COMMENT_ACTIONS = 'SET_COMMENT_ACTIONS';
